version: 2.1

orbs:
  # g33io-dev-repos: orbinoid2/gravitee-dev-repos@0.0.1
  g33io-dev-repos: orbinoid2/gravitee-dev-repos@0.0.2

parameters:
  g33io_to:
    type: string
    # the [default:] clause is required : without it, a Circle CI error will occur
    # default: none
    # the [default:] clause must have a valid value : without a valid value, a Circle CI error will occur
    default: "Gravitee.io Team!"

jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    environment:
      - GREETING_TO_WHOM2: << pipeline.parameters.g33io_to >>
    steps:
      - checkout
      - g33io-dev-repos/greet
          GREETING_TO_WHOM: << pipeline.parameters.g33io_to >>
      - run:
          name: install
          command: npm ci
      - run:
          name: validate
          command: npm run validate
      - run:
          name: release
          command: echo installing semantic-release && npx -p semantic-release@15 -c 'echo running semantic-release && semantic-release'
