version: 2

orbs:
  giodev: orbinoid2/gravitee-dev-repos@0.0.1

jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - giodev/greet
      - run:
          name: install
          command: npm ci
      - run:
          name: validate
          command: npm run validate
      - run:
          name: release
          command: echo installing semantic-release && npx -p semantic-release@15 -c 'echo running semantic-release && semantic-release'
