version: 2.1

orbs:
  gravitee-dev-repos: orbinoid2/gravitee-dev-repos@0.0.1


jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - gravitee-dev-repos/greet
      - run:
          name: install
          command: npm ci
      - run:
          name: validate
          command: npm run validate
      - run:
          name: release
          command: echo installing semantic-release && npx -p semantic-release@15 -c 'echo running semantic-release && semantic-release'
