version: 2.1

orbs:
  g33io-dev-repos: orbinoid2/gravitee-dev-repos@0.0.4
  # g33io-dev-repos: orbinoid2/gravitee-dev-repos@0.0.1

parameters:
  gio_action:
    type: enum
    enum: [product_release, product_release_dry_run, lts_support_release, sts_support_release, dev_pr_review, support_pr_review, build, pull_requests_bot]
    # the [default:] clause is required : without it, a Circle CI error will occur
    # default: none
    # the [default:] clause must have a valid value : without a valid value, a Circle CI error will occur
    default: pull_requests_bot
  pull_req_bot_image_tag:
    type: string
    default: 'stable-latest' # stable -latest is not understood by docker, as "latest" of all tags. So we will use this docker tag to automatically updae / upgrade the Pull Request Bot
    # default: '3.0.76' # we dpo not use explicit version number for docker tag, for us not to be doomed to update a lot of [.circleci/config.yml]
    # default : 'latest' # we never ever use 'latest', but stable-latest

jobs:
  oldschool:
    docker:
      - image: "circleci/node:latest"
    # environment:
      # SOME_PARAM: "some value"
    steps:
      - checkout
      # Will welcome "Gravitee Mates" in the default Team (salesforce)
      - g33io-dev-repos/greet:
          greet_to: "Gravitee Mates"
      # Will welcome Paul, Marc, and Jean in the devops Team
      - gravit33io-devorbs/greet:
          greet_to: "Paul, Marc, Jean"
          greet_team: "devops"
      # Will welcome Alexandre, Yann, and Laurie in the development Team
      - gravit33io-devorbs/greet:
          greet_to: "Alexandre, Yann, Laurie"
          greet_team: "development"
      - run:
          name: install
          command: npm ci
      - run:
          name: validate
          command: npm run validate
      - run:
          name: release
          command: echo installing semantic-release && npx -p semantic-release@15 -c 'echo running semantic-release && semantic-release'

workflows:
  version: 2.1
  wflow_with_old_sch00l_job:
    jobs:
      - oldschool:
          context: cicd-orchestrator
  hell0_workfl0w:
    jobs:
      # Job defined from the [orbinoid2/gravitee-dev-repos@0.0.4] Circle CI Orb
      - g33io-dev-repos/hello-job:
          greet_to: "Titouan, Paul, Nicolas, Azize, David, Florent, Laurie, Rory"
          greet_team: "salesforce"
          context: cicd-orchestrator
